server.port=8080
spring.application.name=order-producer-service
ibm.mq.queueManager=QM1
ibm.mq.channel=DEV.APP.SVRCONN
ibm.mq.connName=localhost(1414)
ibm.mq.user=${MQ_USER}
ibm.mq.password=${MQ_PASSWORD}
app.mq.order-queue=DEV.QUEUE.1
spring.datasource.url=jdbc:postgresql://localhost:5432/order_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
logging.level.com.order.producer=DEBUG

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=producer-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

resilience4j.circuitbreaker.instances.mqProducerService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.mqProducerService.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.mqProducerService.sliding-window-size=5
resilience4j.circuitbreaker.instances.mqProducerService.wait-duration-in-open-state=15s
resilience4j.circuitbreaker.instances.mqProducerService.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.mqProducerService.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.retry.instances.mqProducerRetry.max-attempts=3
resilience4j.retry.instances.mqProducerRetry.wait-duration=2s